name: Application CI
on: [push]
jobs:
    pipeline:
        name: upload pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'
            - name: Build with Maven
              run: mvn -B package --file pom.xml
            - name: Run backend test
              run: |
                  mvn test